### ISSUE TITLE
B: Random crash when clicking the window

### ISSUE THREAD

**Issue by Garfield550** [Garfield550/Year-Progress.NET#1]
```
Application: Year.Progress.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Windows.Window.DragMove()
   at Year.Progress.Views.MainWindow.MoveWindow(System.Object, System.Windows.Input.MouseButtonEventArgs)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventArgs.InvokeHandler(System.Delegate, System.Object)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(System.Object, System.Windows.RoutedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(System.Object, System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseTrustedEvent(System.Windows.RoutedEventArgs)
   at System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs, Boolean)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(System.Windows.Input.InputEventArgs)
   at System.Windows.Input.InputProviderSite.ReportInput(System.Windows.Input.InputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr, System.Windows.Input.InputMode, Int32, System.Windows.Input.RawMouseActions, Int32, Int32, Int32)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr, MS.Internal.Interop.WindowMessage, IntPtr, IntPtr, Boolean ByRef)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at Year.Progress.App.Main()
```

Code: 
https://github.com/Garfield550/Year-Progress.NET/blob/15f98d24a28ff7a6fef504a9901d51890b1672e3/src/Year.Progress/Views/MainWindow.xaml.cs#L24-L27

References:
[Troubleshooting Exceptions: System.InvalidOperationException][1]

[1]: https://msdn.microsoft.com/en-us/library/fd85b3df.aspx#Anchor_1

**Comment by Garfield550** [comment]
https://github.com/Garfield550/Year-Progress.NET/commit/d852ae58a78033078e7d1c56ad7a010b9c298c0f#diff-0109a750b50fef553533402b48cf6b96L14

**Comment by Garfield550** [comment]
Fixed: https://github.com/Garfield550/Year-Progress.NET/commit/d852ae58a78033078e7d1c56ad7a010b9c298c0f#diff-0109a750b50fef553533402b48cf6b96L14

The left mouse button must be down when DragMove is called.

References:

[MSDN: Window.DragMove Method ()][1]

[1]: https://msdn.microsoft.com/en-us/library/system.windows.window.dragmove(v=vs.110).aspx
